on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  
          extensions: mbstring, xml, bcmath, mysql, gd
          tools: composer:v2

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  
          extensions: mbstring, xml, bcmath, curl

      - name: Install Composer dependencies
        run: composer install --optimize-autoloader

      - name: Run migrations
        run: |
          php artisan config:clear
          php artisan migrate --force
        env:
          APP_ENV: local

      - name: Deploy to server via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          rsync -avz -e "ssh -i private_key -o StrictHostKeyChecking=no" ./ $SERVER_USER@$SERVER_IP:www/xn--b1agaam4abxqe.xn--p1ai
          ssh -i private_key -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd www/xn--b1agaam4abxqe.xn--p1ai && git pull origin main && npm run build && php artisan migrate:fresh --force"
