name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  
          extensions: mbstring, xml, bcmath, mysql, gd
          tools: composer:v2

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: webfactory/ssh-agent@v0.5.3
        with:
          host: ${{ secrets.SERVER_IP }}
          user: ${{ secrets.SERVER_USER }}
          ssh-private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          run: |
            ssh -o StrictHostKeyChecking=no user@host "cd /www/xn--b1agaam4abxqe.xn--p1ai && git pull origin main && composer install --no-dev && php artisan migrate --force"
